import type { PaletteItem, PaletteCategory } from '@/types/editor';
import type { UIElementType } from '@/types/spec';

export const paletteItems: PaletteItem[] = [
  // Layout elements
  {
    type: 'row',
    label: 'Row',
    icon: 'LayoutGrid',
    category: 'layout',
    description: 'Horizontal flex container',
    canHaveChildren: true,
    defaultProps: { gap: '4' },
  },
  {
    type: 'column',
    label: 'Column',
    icon: 'LayoutGrid',
    category: 'layout',
    description: 'Vertical flex container',
    canHaveChildren: true,
    defaultProps: { gap: '4' },
  },
  {
    type: 'stack',
    label: 'Stack',
    icon: 'Layers',
    category: 'layout',
    description: 'Stacked layers',
    canHaveChildren: true,
  },
  {
    type: 'grid',
    label: 'Grid',
    icon: 'Grid3x3',
    category: 'layout',
    description: 'CSS Grid container',
    canHaveChildren: true,
    defaultProps: { columns: '3', gap: '4' },
  },
  {
    type: 'card',
    label: 'Card',
    icon: 'CreditCard',
    category: 'layout',
    description: 'Card container with border',
    canHaveChildren: true,
  },
  {
    type: 'section',
    label: 'Section',
    icon: 'SquareDashed',
    category: 'layout',
    description: 'Page section',
    canHaveChildren: true,
  },
  {
    type: 'container',
    label: 'Container',
    icon: 'Square',
    category: 'layout',
    description: 'Generic container',
    canHaveChildren: true,
  },
  {
    type: 'tabs',
    label: 'Tabs',
    icon: 'Folder',
    category: 'layout',
    description: 'Tabbed container',
    canHaveChildren: true,
  },

  // Basic elements
  {
    type: 'text',
    label: 'Text',
    icon: 'Type',
    category: 'basic',
    description: 'Text paragraph',
    defaultProps: { content: 'Text content' },
  },
  {
    type: 'heading',
    label: 'Heading',
    icon: 'Heading',
    category: 'basic',
    description: 'Heading text',
    defaultProps: { level: '2', content: 'Heading' },
  },
  {
    type: 'button',
    label: 'Button',
    icon: 'MousePointer',
    category: 'basic',
    description: 'Clickable button',
    defaultProps: { variant: 'default', content: 'Button' },
  },
  {
    type: 'link',
    label: 'Link',
    icon: 'Link',
    category: 'basic',
    description: 'Hyperlink',
    defaultProps: { href: '#', content: 'Link' },
  },
  {
    type: 'image',
    label: 'Image',
    icon: 'Image',
    category: 'basic',
    description: 'Image element',
    defaultProps: { alt: 'Image' },
  },
  {
    type: 'icon',
    label: 'Icon',
    icon: 'Smile',
    category: 'basic',
    description: 'Icon element',
    defaultProps: { name: 'star' },
  },
  {
    type: 'divider',
    label: 'Divider',
    icon: 'Minus',
    category: 'basic',
    description: 'Horizontal divider',
  },
  {
    type: 'spacer',
    label: 'Spacer',
    icon: 'Space',
    category: 'basic',
    description: 'Empty space',
    defaultProps: { size: '4' },
  },

  // Form elements
  {
    type: 'form',
    label: 'Form',
    icon: 'FileInput',
    category: 'form',
    description: 'Form container',
    canHaveChildren: true,
  },
  {
    type: 'input',
    label: 'Input',
    icon: 'TextCursor',
    category: 'form',
    description: 'Text input field',
    defaultProps: { placeholder: 'Enter text...', type: 'text' },
  },
  {
    type: 'textarea',
    label: 'Textarea',
    icon: 'AlignLeft',
    category: 'form',
    description: 'Multi-line text input',
    defaultProps: { placeholder: 'Enter text...' },
  },
  {
    type: 'select',
    label: 'Select',
    icon: 'ChevronDown',
    category: 'form',
    description: 'Dropdown select',
    canHaveChildren: true,
  },
  {
    type: 'checkbox',
    label: 'Checkbox',
    icon: 'CheckSquare',
    category: 'form',
    description: 'Checkbox input',
    defaultProps: { label: 'Checkbox' },
  },
  {
    type: 'radio',
    label: 'Radio',
    icon: 'Circle',
    category: 'form',
    description: 'Radio button',
    defaultProps: { label: 'Option' },
  },
  {
    type: 'switch',
    label: 'Switch',
    icon: 'ToggleLeft',
    category: 'form',
    description: 'Toggle switch',
    defaultProps: { label: 'Switch' },
  },
  {
    type: 'datepicker',
    label: 'Date Picker',
    icon: 'Calendar',
    category: 'form',
    description: 'Date input',
  },
  {
    type: 'filepicker',
    label: 'File Picker',
    icon: 'Upload',
    category: 'form',
    description: 'File upload',
  },

  // Data elements
  {
    type: 'list',
    label: 'List',
    icon: 'List',
    category: 'data',
    description: 'Data list',
    canHaveChildren: true,
  },
  {
    type: 'table',
    label: 'Table',
    icon: 'Table',
    category: 'data',
    description: 'Data table',
  },
  {
    type: 'chart',
    label: 'Chart',
    icon: 'BarChart',
    category: 'data',
    description: 'Data visualization',
    defaultProps: { type: 'bar' },
  },
  {
    type: 'stat',
    label: 'Stat',
    icon: 'Hash',
    category: 'data',
    description: 'Statistic display',
    defaultProps: { label: 'Stat', value: '0' },
  },

  // Interactive elements
  {
    type: 'modal',
    label: 'Modal',
    icon: 'PanelTop',
    category: 'interactive',
    description: 'Modal dialog',
    canHaveChildren: true,
  },
  {
    type: 'drawer',
    label: 'Drawer',
    icon: 'PanelRight',
    category: 'interactive',
    description: 'Side drawer',
    canHaveChildren: true,
  },
  {
    type: 'tooltip',
    label: 'Tooltip',
    icon: 'MessageSquare',
    category: 'interactive',
    description: 'Hover tooltip',
    canHaveChildren: true,
  },
  {
    type: 'popover',
    label: 'Popover',
    icon: 'MessageCircle',
    category: 'interactive',
    description: 'Click popover',
    canHaveChildren: true,
  },
  {
    type: 'dropdown',
    label: 'Dropdown',
    icon: 'Menu',
    category: 'interactive',
    description: 'Dropdown menu',
    canHaveChildren: true,
  },

  // Structure elements
  {
    type: 'component',
    label: 'Component',
    icon: 'Component',
    category: 'structure',
    description: 'Component reference',
    defaultProps: { ref: '' },
  },
  {
    type: 'slot',
    label: 'Slot',
    icon: 'Plug',
    category: 'structure',
    description: 'Layout slot',
    defaultProps: { name: 'default' },
  },
  {
    type: 'if',
    label: 'Conditional',
    icon: 'GitBranch',
    category: 'structure',
    description: 'Conditional render',
    canHaveChildren: true,
    defaultProps: { condition: '' },
  },
  {
    type: 'each',
    label: 'Loop',
    icon: 'Repeat',
    category: 'structure',
    description: 'Loop over items',
    canHaveChildren: true,
    defaultProps: { items: '', as: 'item' },
  },
  {
    type: 'prompt',
    label: 'Prompt',
    icon: 'Sparkles',
    category: 'structure',
    description: 'LLM guidance for code generation',
    defaultProps: { content: '' },
  },
];

export const categoryLabels: Record<PaletteCategory, string> = {
  layout: 'Layout',
  basic: 'Basic',
  form: 'Form',
  data: 'Data',
  interactive: 'Interactive',
  structure: 'Structure',
};

export const categoryOrder: PaletteCategory[] = [
  'layout',
  'basic',
  'form',
  'data',
  'interactive',
  'structure',
];

export function getPaletteItemsByCategory(category: PaletteCategory): PaletteItem[] {
  return paletteItems.filter((item) => item.category === category);
}

export function getPaletteItem(type: UIElementType): PaletteItem | undefined {
  return paletteItems.find((item) => item.type === type);
}
